In [1]:
import sys
sys.executable

'C:\\Users\\Admin\\anaconda3\\envs\\min_ds-env\\python.exe'

In [2]:
import pandas as pd
import os
import numpy as np

In [3]:
DATA_DIR = './data/stack-overflow-developer-survey-2021/'

In [4]:
files = !ls $DATA_DIR 
files = [file for file in files if '.csv' in file]
files

['survey_results_public.csv', 'survey_results_schema.csv']

In [5]:
df1 = pd.read_csv(os.path.join(DATA_DIR, files[0]))
df1

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83435,83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83436,83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83437,83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83438,83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,...,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

### Questions

#### How many rows and columns?

In [6]:
num_rows, num_cols = df1.shape
num_rows, num_cols

(83439, 48)

#### What is the meaning of each row?

Each row shows survey information from each user.

#### Are there duplicated rows?

In [7]:
have_duplicated_rows = df1.duplicated().any()
have_duplicated_rows

False

There are no duplicated row.

#### What is the meaning of each column?

In [8]:
cols = ['MainBranch', 'Employment', 'Country', 'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode', 'YearsCodePro',
        'DevType', 'OrgSize','Currency', 'CompTotal', 'CompFreq', 'ConvertedCompYearly', 'LanguageHaveWorkedWith',
        'LanguageWantToWorkWith', 'LanguageWantToWorkWith', 'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 
        'NEWCollabToolsWantToWorkWith', 'NEWCollabToolsHaveWorkedWith', 'OpSys', 'Age', 'Gender' ]
    
numerical_cols = ['YearsCode', 'YearsCodePro', 'CompTotal', 'ConvertedCompYearly']

categorical_cols = ['MainBranch', 'Employment', 'Country', 'EdLevel', 'Age1stCode',
                    'DevType', 'OrgSize', 'Currency', 'CompFreq', 'OpSys', 'Age', 'Gender']

In the above dataset, we only single out certain columns to use.
- MainBranch
- Employment 
- Country 
- EdLevel : Education level
- Age1stCode: The age at which they first code
- LearnCode: Where they learn code.
- YearsCode: Number of years they have been coding
- YearsCodePro: number of years they have been coding professionally
- DevType:  type of developer
- OrgSize: size of the companies they are working at
- Currency
- CompTotal: salary earned per unit of time.
- CompFreq: time unit of CompTotal
- ConvertedCompYearly: converted yearly compensation in US dollar
- LanguageHaveWorkedWith : languages they have worked with
- LanguageWantToWorkWith
- MiscTechHaveWorkedWith: NumpY, TensorFlow, Flutter, Qt
- MiscTechWantToWorkWith
- OpSys: Their primary operating system
- Age: Age group they belong to
- NEWCollabToolsWantToWorkWith: developmenet environment (Vim,PyCharm, Notepad, Sublime,...)
- NEWCollabToolsHaveWorkedWith: developmenet environment (Vim,PyCharm, Notepad, Sublime,...)
- Gender

#### What is the current data type of each column?

Create main data frame.

In [9]:
main_df = df1[cols]
main_df

,MainBranch,Employment,Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,...,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsHaveWorkedWith,OpSys,Age,Gender
0,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,...,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,Swift,NaN,NaN,Atom;Xcode,PHPStorm;Xcode,MacOS,25-34 years old,Man
1,I am a student who is learning to code,"Student, full-time",Netherlands,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,...,JavaScript;Python,NaN,NaN,Cordova,NaN,NaN,Android Studio;IntelliJ;Notepad++;PyCharm,Windows,18-24 years old,Man
2,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,...,Assembly;C;Python;R;Rust,Julia;Python;Rust,Julia;Python;Rust,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,IPython/Jupyter;RStudio;Sublime Text;Visual St...,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,MacOS,18-24 years old,Man
3,I am a developer by profession,Employed full-time,Austria,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,...,JavaScript;TypeScript,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Windows,35-44 years old,Man
4,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",...,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Linux-based,25-34 years old,Man
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,I am a developer by profession,Employed full-time,United States of America,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,"Developer, back-end",20 to 99 employees,...,Clojure;Kotlin;SQL,Clojure,Clojure,NaN,NaN,Sublime Text;Vim,IntelliJ;Sublime Text;Vim;Visual Studio Code,MacOS,25-34 years old,Man
83435,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",...,NaN,NaN,NaN,Flutter;Qt,NaN,Emacs;IntelliJ;PHPStorm;PyCharm;RStudio;Sublim...,Android Studio;Eclipse;Emacs;IntelliJ;NetBeans...,Linux-based,18-24 years old,Man
83436,I am a developer by profession,Employed full-time,United States of America,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",...,Groovy;Java;Python,Java;Python,Java;Python,Hadoop;Keras;NumPy;Pandas,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorFlow,IntelliJ;IPython/Jupyter;Notepad++;Vim,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,Windows,25-34 years old,Man
83437,I am a developer by profession,Employed full-time,Canada,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,...,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Go;Rust,NumPy;Pandas;TensorFlow;Torch/PyTorch,NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,PyCharm;Sublime Text,MacOS,25-34 years old,Man
83438,I am a developer by profession,Employed full-time,Brazil,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,...,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,NaN,NaN,IntelliJ;PHPStorm;Visual Studio Code,IntelliJ;Visual Studio Code,Linux-based,18-24 years old,Man

In [10]:
main_df.dtypes

MainBranch                       object
Employment                       object
Country                          object
EdLevel                          object
Age1stCode                       object
LearnCode                        object
YearsCode                        object
YearsCodePro                     object
DevType                          object
OrgSize                          object
Currency                         object
CompTotal                       float64
CompFreq                         object
ConvertedCompYearly             float64
LanguageHaveWorkedWith           object
LanguageWantToWorkWith           object
LanguageWantToWorkWith           object
MiscTechHaveWorkedWith           object
MiscTechWantToWorkWith           object
NEWCollabToolsWantToWorkWith     object
NEWCollabToolsHaveWorkedWith     object
OpSys                            object
Age                              object
Gender                           object
dtype: object

#### Are there columns having inappropriate data types?

In [11]:
main_df[numerical_cols].dtypes

YearsCode               object
YearsCodePro            object
CompTotal              float64
ConvertedCompYearly    float64
dtype: object

"YearsCode" and "YearsCodePro" of numerical_cols still have the object data types, so we will return the set of data types actually present in those columns.

In [12]:
def open_object_dtype(s):
    
    dtypes = set(s.apply(type).unique())
    
    return dtypes

In [13]:
print(open_object_dtype(main_df['YearsCode']))
print(open_object_dtype(main_df['YearsCodePro']))

{<class 'str'>, <class 'float'>}
{<class 'str'>, <class 'float'>}

Convert dtype of columns "YearsCode" and "YearsCodePro" to float.

In [14]:
main_df['YearsCode'] = pd.to_numeric(main_df['YearsCode'], errors='coerce')
main_df['YearsCodePro'] = pd.to_numeric(main_df['YearsCodePro'], errors='coerce')

C:\Users\Admin\AppData\Local\Temp/ipykernel_12960/170766153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['YearsCode'] = pd.to_numeric(main_df['YearsCode'], errors='coerce')
C:\Users\Admin\AppData\Local\Temp/ipykernel_12960/170766153.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['YearsCodePro'] = pd.to_numeric(main_df['YearsCodePro'], errors='coerce')

In [15]:
main_df[numerical_cols].dtypes

YearsCode              float64
YearsCodePro           float64
CompTotal              float64
ConvertedCompYearly    float64
dtype: object

#### With each numerical column, how are values distributed?
- What is the percentage of missing values?
- Min? max? Are they abnormal?

In [17]:
def missing_ratio(s):
    return s.isna().mean() * 100

In [40]:
nume_col_profiles_df = main_df[numerical_cols]
nume_col_profiles_df = nume_col_profiles_df.agg([missing_ratio, pd.Series.min, pd.Series.max])
nume_col_profiles_df.round(2)

               YearsCode  YearsCodePro     CompTotal  ConvertedCompYearly
missing_ratio       4.14         29.93  4.345000e+01                43.86
min                 1.00          1.00  0.000000e+00                 1.00
max                50.00         50.00  1.000000e+74          45241312.00

Không có gì bất thường.

#### With each categorical column, how are values distributed?
- What is the percentage of missing values?
- How many different values? Show a few
- Are they abnormal?

In [41]:
def diff_vals(s):
    return s.dropna().unique()

In [42]:
cate_col_profiles_df = main_df[categorical_cols]
cate_col_profiles_df = cate_col_profiles_df.agg([missing_ratio, pd.Series.nunique, diff_vals])
cate_col_profiles_df = cate_col_profiles_df.rename(index={'nunique': 'num_diff_vals'})
cate_col_profiles_df

,MainBranch,Employment,Country,EdLevel,Age1stCode,DevType,OrgSize,Currency,CompFreq,OpSys,Age,Gender
missing_ratio,0.0,0.139024,0.0,0.375124,0.234902,20.320234,27.221084,26.796822,37.499251,0.17378,1.236832,1.381848
num_diff_vals,6,9,181,9,9,8626,10,146,3,6,8,16
diff_vals,"[I am a developer by profession, I am a studen...","[Independent contractor, freelancer, or self-e...","[Slovakia, Netherlands, Russian Federation, Au...","[Secondary school (e.g. American high school, ...","[18 - 24 years, 11 - 17 years, 5 - 10 years, 2...","[Developer, mobile, Developer, front-end, Deve...","[20 to 99 employees, 100 to 499 employees, Jus...","[EUR European Euro, GBP\tPound sterling, INR\t...","[Monthly, Yearly, Weekly]","[MacOS, Windows, Linux-based, BSD, Other (plea...","[25-34 years old, 18-24 years old, 35-44 years...","[Man, Prefer not to say, Woman, Non-binary, ge..."

Không có điều gì bất thường.